name: Stream Service
on:
  workflow_dispatch:
jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
      - name: Start Live
        run: |
          while true; do
            # ملاحظة: استبدل الرابط أدناه برابط فيديو مباشر ينتهي بـ .mp4
            ffmpeg -re -i "https://files.catbox.moe/p9r17x.mp4" -c:v libx264 -preset ultrafast -b:v 2500k -c:a aac -f flv "rtmp://a.rtmp.youtube.com/live2/q12g-s6wc-0y03-0ua5-6e6p"
            sleep 5
          done
